service: serverless-sequelize

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
     - http:
        path: users
        method: get
        cors: true
