version: '3'
services:
  app-nodejs:
    build: .
    container_name: node_app_pg
    ports:
      - "8080:3000"
    depends_on:
     - db
    environment:
      - HOST=db
      - NODE_ENV=production
  db:
    image: postgres
    container_name: node_db_pg
    ports:
      - "5432:5432"
    volumes:
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: secret1189
