service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 3

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 3

  add:
    handler: add.add
    memorySize: 256
    timeout: 10
    events:
     - http:
        path: math/add
        method: post
        cors: true
