version: '3'

services:
  app-nodejs:
    build: .
    environment:
      PORT: 4000
    container_name: nodejs-express
    ports:
      - "8080:4000"
    volumes:
      - ./:/home/node/app
      - /usr/src/app/node_modules
